name: "Kiko++"

language: 'en'

author:
  # facebook: 
  # youtubeUser: 
  # youtubeChannel: 
  # twitter: 
  # github: 
  # stackoverflow: 
  # quora: 
  # linkedin: 
  # pinterest: 
  # googlePlus: 
  # instagram: 
  # reddit: 
  # medium: 
  # tumblr: 
  # email: 

copyright:
  year: 2020
  name: Kiko++

google-analytics:
  # id: ""

disqus:
  # id: ""

url: "https://sangwon090.github.io"
baseurl: ""

timezone: Asia/Seoul
permalink: /:year-:month-:day/:title/

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  title: ':title'
  permalink: '/page/:num/'
  trail: 
    before: 2
    after: 2

markdown: kramdown

kramdown:
  input: GFM

nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
  - name: "Tags"
    url: "/tags"
  - name: "Github"
    url: "https://github.com/sangwon090/Kiko-PlusPlus"

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-admin